let libros=[ 
     {
            titulo: "El Principito",
            autor: "Antoine de Saint-Exupéry",
            genero: "Ficción",
            idioma: "Español",
            precio: "Depende del vendedor y la edición",
            formato: "Puede estar disponible en tapa dura, tapa blanda y ebook, entre otros",
            ISBN: "ISBN para la edición en español es: 9788490431604",
            Descripcion: "Es una novela corta que narra la historia de un joven príncipe que viaja por diferentes planetas",
            estado: "nuevo",
            ubicacion: "Disponible en librerías físicas y tiendas en línea",
            fechadepublicacion: "Originalmente publicado en 1943",
            editorial: "iEditorial Siruela",
            paginas: "Varía según la edición, generalmente alrededor de 100 páginas",
            dimensiones: "Alrededor de 13 x 1 x 20 cm (ancho x profundidad x altura) en tapa blanda",
            peso: "Alrededor de 100-200 gramos en tapa blanda",
        },
        {
            
                titulo: "Cien años de soledad",
                autor: "Gabriel García Márquez",
                genero: "Ficción",
                idioma: "Español",
                precio: "Depende del vendedor y la edición",
                formato: "Disponible en tapa dura, tapa blanda y ebook, entre otros",
                ISBN: " ISBN para la edición en español es: 978-84-376-0494-7",
                Descripcion: "Es una novela que narra la historia de la familia Buendía a lo largo de varias generaciones en el ficticio pueblo de Macondo.",
                estado: "Nuevo",
                ubicacion: "Disponible en librerías físicas y tiendas en línea",
                fechadepublicacion: "Originalmente publicado en 1967",
                editorial:"Editorial Sudamericana",
                paginas: "Varía según la edición, generalmente alrededor de 500 páginas",
                dimensiones: "Alrededor de 15 x 3 x 23 cm (ancho x profundidad x altura) en tapa blanda",
                peso: "Alrededor de 400-600 gramos en tapa blanda",
            
        },
        
           {
              titulo: "Don Quijote de la Mancha",
              autor: "Miguel de Cervantes",
              genero: "Ficción",
              idioma: "Español",
              precio: "Variable según la edición y vendedor",
              formato: "Tapa dura, tapa blanda, ebook, entre otros",
              ISBN: "Depende de la edición",
              descripcion: "Una de las obras más importantes de la literatura española, que narra las aventuras de un hidalgo que se cree caballero andante.",
              estado: "Nuevo",
              ubicacion: "Disponible en librerías físicas y tiendas en línea",
              fechaDePublicacion: "Primera parte publicada en 1605, segunda parte en 1615",
              editorial: "Varias editoriales han publicado ediciones, como Editorial Espasa-Calpe",
              paginas: "Varía según la edición, generalmente alrededor de 1000 páginas",
              dimensiones: "Depende del formato",
              peso: "Depende del formato"
            },
          {
              titulo: "Harry Potter y la piedra filosofal",
              autor: "J.K. Rowling",
              genero: "Ficción, Fantasía",
              idioma: "Español",
              precio: "Variable según la edición y vendedor",
              formato: "Tapa dura, tapa blanda, ebook, entre otros",
              ISBN: "Depende de la edición",
              descripcion: "El primer libro de la famosa serie de Harry Potter, que narra las aventuras del joven mago en el Colegio Hogwarts de Magia y Hechicería.",
              estado: "Nuevo",
              ubicacion: "Disponible en librerías físicas y tiendas en línea",
              fechaDePublicacion: "Originalmente publicado en 1997",
              editorial: "Salamandra",
              paginas: "Varía según la edición, generalmente alrededor de 300 páginas",
              dimensiones: "Depende del formato",
              peso: "Depende del formato"
            },
           {
                titulo: "La Odisea",
                autor: "Homero",
                genero: "Poesía épica",
                idioma: "Español (traducción)",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa dura, tapa blanda, ebook, entre otros",
                ISBN: "Depende de la edición",
                descripcion: "Un poema épico que relata el viaje de Ulises de vuelta a casa después de la Guerra de Troya.",
                estado: "Nuevo",
                ubicacion: "Disponible en librerías físicas y tiendas en línea",
                fechaDePublicacion: "Antigua, fecha aproximada siglo VIII a.C.",
                editorial: "Varias editoriales han publicado ediciones, como Alianza Editorial",
                paginas: "Varía según la edición, generalmente alrededor de 400 páginas",
                dimensiones: "Depende del formato",
                peso: "Depende del formato"
              },
             {
                titulo: "Moby Dick",
                autor: "Herman Melville",
                genero: "Ficción, Novela marítima",
                idioma: "Español (traducción)",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa dura, tapa blanda, ebook, entre otros",
                ISBN: "Depende de la edición",
                descripcion: "La historia del capitán Ahab y su obsesión por cazar a la gran ballena blanca, Moby Dick.",
                estado: "Nuevo",
                ubicacion: "Disponible en librerías físicas y tiendas en línea",
                fechaDePublicacion: "Originalmente publicado en 1851",
                editorial: "Varias editoriales han publicado ediciones, como Penguin Clásicos",
                paginas: "Varía según la edición, generalmente alrededor de 600 páginas",
                dimensiones: "Depende del formato",
                peso: "Depende del formato"
              },
            {
                titulo: "Crimen y castigo",
                autor: "Fyodor Dostoevsky",
                genero: "Ficción, Novela psicológica",
                idioma: "Español (traducción)",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa dura, tapa blanda, ebook, entre otros",
                ISBN: "Depende de la edición",
                descripcion: "La historia de un estudiante llamado Raskólnikov que comete un asesinato y enfrenta las consecuencias psicológicas de sus acciones.",
                estado: "Nuevo",
                ubicacion: "Disponible en librerías físicas y tiendas en línea",
                fechaDePublicacion: "Originalmente publicado en 1866",
                editorial: "Varias editoriales han publicado ediciones, como Penguin Clásicos",
                paginas: "Varía según la edición, generalmente alrededor de 600 páginas",
                dimensiones: "Depende del formato",
                peso: "Depende del formato"
              },
             {
                titulo: "Rayuela",
                autor: "Julio Cortázar",
                genero: "Ficción, Experimental",
                idioma: "Español",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa dura, tapa blanda, ebook, entre otros",
                ISBN: "Depende de la edición",
                descripcion: "Una novela que desafía las convenciones narrativas tradicionales y presenta múltiples formas de lectura.",
                estado: "Nuevo",
                ubicacion: "Disponible en librerías físicas y tiendas en línea",
                fechaDePublicacion: "Originalmente publicado en 1963",
                editorial: "Varias editoriales han publicado ediciones, como Alfaguara",
                paginas: "Varía según la edición, generalmente alrededor de 600 páginas",
                dimensiones: "Depende del formato",
                peso: "Depende del formato"
              },
              {
                titulo: "Los miserables",
                autor: "Victor Hugo",
                genero: "Ficción, Novela histórica",
                idioma: "Español (traducción)",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa dura, tapa blanda, ebook, entre otros",
                ISBN: "Depende de la edición",
                descripcion: "La historia de Jean Valjean y su lucha por la redención en la Francia del siglo XIX.",
                estado: "Nuevo",
                ubicacion: "Disponible en librerías físicas y tiendas en línea",
                fechaDePublicacion: "Originalmente publicado en 1862",
                editorial: "Varias editoriales han publicado ediciones, como Penguin Clásicos",
                paginas: "Varía según la edición, generalmente alrededor de 1500 páginas",
                dimensiones: "Depende del formato",
                peso: "Depende del formato"
              },
             {
                titulo: "El retrato de Dorian Gray",
                autor: "Oscar Wilde",
                genero: "Ficción, Novela gótica",
                idioma: "Español (traducción)",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa dura, tapa blanda, ebook, entre otros",
                ISBN: "Depende de la edición",
                descripcion: "La historia de un hombre joven cuyo retrato envejece mientras él permanece eternamente joven.",
                estado: "Nuevo",
                ubicacion: "Disponible en librerías físicas y tiendas en línea",
                fechaDePublicacion: "Originalmente publicado en 1890",
                editorial: "Varias editoriales han publicado ediciones, como Penguin Clásicos",
                paginas: "Varía según la edición, generalmente alrededor de 250 páginas",
                dimensiones: "Depende del formato",
                peso: "Depende del formato"
              },
             {
                titulo: "El señor de los anillos: La Comunidad del Anillo",
                autor: "J.R.R. Tolkien",
                genero: "Ficción, Fantasía épica",
                idioma: "Español (traducción)",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa dura, tapa blanda, ebook, entre otros",
                ISBN: "Depende de la edición",
                descripcion: "La primera parte de la trilogía épica que sigue la búsqueda del Anillo Único por parte de Frodo Bolsón y su compañía.",
                estado: "Nuevo",
                ubicacion: "Disponible en librerías físicas y tiendas en línea",
                fechaDePublicacion: "Originalmente publicado en 1954",
                editorial: "Varias editoriales han publicado ediciones, como Minotauro",
                paginas: "Varía según la edición, generalmente alrededor de 500 páginas",
                dimensiones: "Depende del formato",
                peso: "Depende del formato"
              },
              {
                titulo: "La metamorfosis",
                autor: "Franz Kafka",
                genero: "Ficción, Novela corta",
                idioma: "Español (traducción)",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa dura, tapa blanda, ebook, entre otros",
                ISBN: "Depende de la edición",
                descripcion: "La historia de Gregor Samsa, quien se despierta un día transformado en un insecto gigante.",
                estado: "Nuevo",
                ubicacion: "Disponible en librerías físicas y tiendas en línea",
                fechaDePublicacion: "Originalmente publicado en 1915",
                editorial: "Varias editoriales han publicado ediciones, como Alianza Editorial",
                paginas: "Varía según la edición, generalmente alrededor de 100 páginas",
                dimensiones: "Depende del formato",
                peso: "Depende del formato"
              },
              {
                titulo: "La divina comedia",
                autor: "Dante Alighieri",
                genero: "Poesía épica, Alegoría",
                idioma: "Español (traducción)",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa dura, tapa blanda, ebook, entre otros",
                ISBN: "Depende de la edición",
                descripcion: "Un poema épico que narra el viaje de Dante a través del Infierno, el Purgatorio y el Paraíso.",
                estado: "Nuevo",
                ubicacion: "Disponible en librerías físicas y tiendas en línea",
                fechaDePublicacion: "Originalmente publicado en 1320",
                editorial: "Varias editoriales han publicado ediciones, como Penguin Clásicos",
                paginas: "Varía según la edición, generalmente alrededor de 700 páginas",
                dimensiones: "Depende del formato",
                peso: "Depende del formato"
              },       
              {
                titulo: "Hamlet",
                autor: "William Shakespeare",
                genero: "Tragedia, Drama",
                idioma: "Español (traducción)",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa dura, tapa blanda, ebook, entre otros",
                ISBN: "Depende de la edición",
                descripcion: "Una de las tragedias más famosas de Shakespeare, que sigue al príncipe Hamlet en su búsqueda de venganza por la muerte de su padre.",
                estado: "Nuevo",
                ubicacion: "Disponible en librerías físicas y tiendas en línea",
                fechaDePublicacion: "Originalmente publicado entre 1599 y 1602",
                editorial: "Varias editoriales han publicado ediciones, como Penguin Clásicos",
                paginas: "Varía según la edición, generalmente alrededor de 300 páginas",
                dimensiones: "Depende del formato",
                peso: "Depende del formato"
              },
             {
                titulo: "La guerra y la paz",
                autor: "Lev Tolstói",
                genero: "Ficción, Novela histórica",
                idioma: "Español (traducción)",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa dura, tapa blanda, ebook, entre otros",
                ISBN: "Depende de la edición",
                descripcion: "Una novela monumental que narra las vidas de varias familias aristocráticas rusas durante la invasión napoleónica.",
                estado: "Nuevo",
                ubicacion: "Disponible en librerías físicas y tiendas en línea",
                fechaDePublicacion: "Originalmente publicado entre 1865 y 1869",
                editorial: "Varias editoriales han publicado ediciones, como Debolsillo",
                paginas: "Varía según la edición, generalmente alrededor de 1500 páginas",
                dimensiones: "Depende del formato",
                peso: "Depende del formato"
              },
              {
                titulo: "Fahrenheit 451",
                autor: "Ray Bradbury",
                genero: "Ficción, Distopía",
                idioma: "Español (traducción)",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa dura, tapa blanda, ebook, entre otros",
                ISBN: "Depende de la edición",
                descripcion: "Una novela que presenta una sociedad futurista donde los libros están prohibidos y son quemados por bomberos.",
                estado: "Nuevo",
                ubicacion: "Disponible en librerías físicas y tiendas en línea",
                fechaDePublicacion: "Originalmente publicado en 1953",
                editorial: "Varias editoriales han publicado ediciones, como Debolsillo",
                paginas: "Varía según la edición, generalmente alrededor de 250 páginas",
                dimensiones: "Depende del formato",
                peso: "Depende del formato"
              },
              {
                titulo: "Las Crónicas de Narnia: El león, la bruja y el armario",
                autor: "C.S. Lewis",
                genero: "Fantasía",
                idioma: "Español",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa blanda",
                isbn: "9780007115617",
                descripcion: "Cuatro niños descubren un mundo mágico detrás de un armario en una casa de campo.",
                estado: "Nuevo",
                ubicacion: "Librería Lewis",
                fecha_publicacioo: "16 de octubre de 1950",
                editorial: "HarperCollins",
                paginas: "Varía según la edición, generalmente alrededor de 208 páginas",
                dimensiones: "Depende del formato", 
                peso: "Depende del formato"
            },
        
                {
                titulo: "Orgullo y prejuicio",
                autor: "Jane Austen",
                genero: "Novela romántica",
                idioma: "Español",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa blanda",
                isbn: "9788491040541",
                descripcion: "La compleja historia de amor entre Elizabeth Bennet y Mr. Darcy en la Inglaterra del siglo XIX.",
                estado: "Nuevo",
                ubicacion: "Librería Austen",
                fecha_publicacioo: "28 de enero de 1813",
                editorial: "Alba Editorial",
                paginas:"Varía según la edición, generalmente alrededor de 420 páginas",
                dimensiones: "Depende del formato", 
                peso:  "Depende del formato"
             },
             {
                titulo: "Veinte mil leguas de viaje submarino",
                autor: "Jules Verne",
                genero: "Novela",
                idioma: "Español",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa dura",
                isbn: "9788499084565",
                descripcion: "La historia de un viaje en un submarino a través de los mares del mundo.",
                estado: "Nuevo",
                ubicacion: "Librería Mágica",
                fecha_publicacioo: "20 de marzo de 1870",
                editorial: "Alianza",
                paginas: "Varía según la edición, generalmente alrededor de 240 páginas",
                dimensiones:"Depende del formato", 
                peso: "Depende del formato"
             },
             {
                titulo: "La Isla del Tesoro",
                autor: "Robert Louis Stevenson",
                genero: "Aventuras",
                idioma: "Español",
                precio: "Variable según la edición y vendedor",
                formato: "Tapa blanda",
                isbn: "9788466655522",
                descripcion: "La historia de un joven que busca un tesoro en una isla misteriosa.",
                estado: "Nuevo",
                ubicacion: "Librería Mágica",
                fecha_publicacioo: "23 de noviembre de 1883",
                editorial: "Alianza",
                paginas:"Varía según la edición, generalmente alrededor de 240 páginas",
                dimensiones: "Depende del formato", 
                peso:  "Depende del formato"
                },
     ];
        
   
     newbook={
      titulo: prompt("titulo"),
      autor: prompt("titulo"),
      genero: prompt("titulo"),
      idioma: prompt("titulo"),
      precio: prompt("titulo"),
      formato: prompt("titulo"),
      isbn: prompt("titulo"),
      descripcion: prompt("titulo"),
      estado: prompt("titulo"),
      ubicacion: prompt("titulo"),
      fecha_publicacion: prompt("titulo"),
      editorial: prompt("titulo"),
      paginas: prompt("titulo"),
      dimensiones: prompt("titulo"), 
      peso:prompt("titulo") 
  }
  libros.push(newbook)
console.log(libros)
  


